#!/bin/bash

mp=/mnt/tmp
img=/var/tmp/test.img
fs_mark_logdir=/var/tmp/fs_log.out
dirs1=5 # first-level directories
dirs2=5 # second-level directories

KiB=1024
MiB=$((1024*1024))
bsize=$((4 * KiB))
MINAGSIZE=$((64 * bsize)) # minimum size before a new AG gets created

start_size=$(( 300 * MiB ))
image_size=$(( start_size + MINAGSIZE + (7 * bsize) ))

if [[ -z $FS_MARK ]] || [[ ! -x $FS_MARK ]] ; then
	FS_MARK=$(which fs_mark)
	[[ ! -x $FS_MARK ]] && {
		echo "unable to find 'fs_mark'"
		echo "please install fs_mark (https://github.com/josefbacik/fs_mark)"
		echo "  and either add fs_mark to one of the system paths,"
		echo "  or use FS_MARK=<PATH> to specify its location"
		exit 1
	}
fi

while true ; do
	out=$(umount -f $mp 2>&1)
	[[ $out =~ "not mounted" ]] && break
	[[ $out =~ "no mount point specified." ]] && break
	[[ $out =~ "target is busy" ]] && echo "unable to unmount $mp ... busy filesystem" && exit 1
done

rm -f $img
truncate -s $image_size $img
mkfs.xfs -dsize=$start_size $img || exit
mkdir -p $mp
mount $img $mp

xfs_io -xc 'resblks 0' $mp	# no reserved blocks
xfs_growfs -d -m 100 $mp	# inode % to 100, and grow the fs if possible

interrupted() {
	trap - SIGINT SIGTERM EXIT
	rm -f /tmp/.run
	run_time=$(($SECONDS - start_time))
	dmesg | grep -q corrupt && echo "reproduced in $((SECONDS - start_time)) seconds"
	exit
}
trap interrupted SIGINT SIGTERM EXIT

# dynamically build the list of directories
paths=$(for i in $(seq 0 $((dirs1 - 1))) ; do echo -n " -d $mp/d$i" ; done)

dmesg -c >/dev/null
touch /tmp/.run
rm -rf $fs_mark_logdir
mkdir -p $fs_mark_logdir
start_time=$SECONDS
while [[ -e /tmp/.run ]] ; do
	$FS_MARK -k -F -S 0 -D $dirs2 -N 1000 -s 0 -p 16 -l $fs_mark_logdir/fs_log.txt $paths
	dmesg | grep corrupt -A1 && break

	## not reproduced... delete something and restart
	dir1=$(cd $mp && ls -1fd * | sort -R | head -n1)
	dir2=$(cd $mp/$dir1 && ls -1fd * | sort -R | head -n1)

	echo "run time $((SECONDS - start_time)) seconds - deleting $mp/$dir1/$dir2"
#	rm -rf $mp/$dir1/$dir2
	find $mp/$dir1/$dir2 -type f -delete
done
