#!/bin/bash

input=${1:--}

grep getdents $input | sed -e 's/, {{d_ino/, [{d_ino/g' -e 's/}}, \([0-9]\+\)/}], \1/g' -e 's/\} {d_ino/}, {d_ino/g' \
	-e 's/\({d_ino[^}]\+\)/\n    \1/g' \
	-e 's/, {}, \([0-9]\+\)/, [], \1/g' \
	-e 's/}\(}, .\+$\)/},\n\1/g' \
	-e 's/, \([0-9]\+\))/,\n    \1/g' \
	| sed -e 's/}],$/}\n    ],/g'
