#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <sched.h>

char *conf_path = "/etc/init/control-alt-delete.conf";
char *override_path = "/etc/init/control-alt-delete.override";

char conf_contents_orig[] = "# control-alt-delete - emergency keypress handling\n"
"#\n"
"# This task is run whenever the Control-Alt-Delete key combination is\n"
"# pressed.  Usually used to shut down the machine.\n"
"#\n"
"# Do not edit this file directly. If you want to change the behaviour,\n"
"# please create a file control-alt-delete.override and put your changes there.\n"
"\n"
"start on control-alt-delete\n"
"\n"
"#exec /sbin/shutdown -r now \"Control-Alt-Delete pressed\"\n"
"exec /usr/bin/logger -p security.info \"Ctrl-Alt-Delete pressed\"\n"
"";

char conf_contents_new[] = "# control-alt-delete - emergency keypress handling\n"
"#\n"
"# This task is run whenever the Control-Alt-Delete key combination is\n"
"# pressed.  Usually used to shut down the machine.\n"
"#\n"
"# Do not edit this file directly. If you want to change the behaviour,\n"
"# please create a file control-alt-delete.override and put your changes there.\n"
"\n"
"start on control-alt-delete\n"
"\n"
"exec /sbin/shutdown -r now \"Control-Alt-Delete pressed\"\n"
"";

char override_contents[] = "-----------------------------------------------------------------------\n"
"# control-alt-delete - emergency keypress handling\n"
"#\n"
"\n"
"exec /usr/bin/logger -p security.info \"Ctrl-Alt-Delete pressed\"\n"
"";

void write_file(char *path, char *contents, size_t len) {
	int fd;
	struct stat st;

	stat(path, &st);
	fd = open(path, O_CREAT | O_TRUNC | O_WRONLY, 0644);
	sched_yield();
	write(fd, contents, len);
	close(fd);
}

void restore_pre_upgrade(void) {
	unlink(override_path);
	sched_yield();
	write_file(conf_path, conf_contents_orig, sizeof(conf_contents_orig));
}
void try_crash(void) {
	write_file(override_path, override_contents, sizeof(override_contents));
	write_file(conf_path, conf_contents_new, sizeof(conf_contents_new));
}
int main(int argc, char *argv[]) {

	while (1) {
		restore_pre_upgrade();
		sync();
		usleep(250000);

		try_crash();
		sync();
		usleep(250000);
	}
	/* we're trying to panic... if we get here, we've failed to fail */
	return EXIT_FAILURE;
}
